### ISSUE TITLE
cgroup_exporter not seeing slurm jobs started on host....

### ISSUE THREAD

**Issue by jeff-avila** [PrincetonUniversity/jobstats#10]
Hi All, quick question on getting jobstats to work-

I've got a test cluster with four nodes, two cpu, one gpu, & and a slurmctld/slurmdbd host.
My dummy jobs ('sleep 300', or a sysbench run) don't seem to show up in jobstats-for instance, on my latest 
'sleep 300' run, I had a jobid of 850:

`[root@control jobstats]# ./jobstats 850
Traceback (most recent call last):
  File "/root/jobstats/./jobstats", line 58, in <module>
    stats.report_job()
  File "/root/jobstats/jobstats.py", line 579, in report_job
    self.error(f"No stats found for job {self.jobid}, either because it is too old or because\n"
  File "/root/jobstats/jobstats.py", line 115, in error
    raise Exception(msg)
Exception: No stats found for job 850, either because it is too old or because
it expired from jobstats database. If you are not running this command on the
cluster where the job was run then use the -c option to specify the cluster.
If the run time was very short then try running "seff 850".
[root@control jobstats]#`

The job did, in fact, run:
(from sacct)

850            gen_work      batch    default          2  COMPLETED      0:0
850.batch         batch               default          1  COMPLETED      0:0
850.extern       extern               default          2  COMPLETED      0:0

A quick glance at the webpage for the cgroup_exporter on the node the job ran on...shows nothing if I Ctrl-F search for either 'slurm' or '850'. I've cloned the latest cgroupv2 branch of the exporter, and built it w/o issue:

[root@node01 ~]# /usr/sbin/cgroup_exporter -h
usage: cgroup_exporter --config.paths=CONFIG.PATHS [<flags>]

Flags:
  -h, --[no-]help               Show context-sensitive help (also try --help-long and --help-man).
      --config.paths=CONFIG.PATHS
                                Comma separated list of cgroup paths to check, eg /user.slice,/system.slice,/slurm
      --web.listen-address=":9306"
                                Address to listen on for web interface and telemetry.
      --[no-]web.disable-exporter-metrics
                                Exclude metrics about the exporter (promhttp_*, process_*, go_*)
      --path.cgroup.root="/sys/fs/cgroup"
                                Root path to cgroup fs
      --[no-]collect.fullslurm  Boolean that sets if to collect all slurm steps and tasks
      --log.level=info          Only log messages with the given severity or above. One of: [debug, info, warn, error]
      --log.format=logfmt       Output format of log messages. One of: [logfmt, json]
      --[no-]version            Show application version.

(from systemctl)

CGroup: /system.slice/cgroup_exporter.service
             └─3349833 /usr/sbin/cgroup_exporter --web.listen-address=0.0.0.0:9306 --config.paths /slurm --collect.full

Again, I feel like there should be some record of jobs starting on this node if I go to node01:9306 and search for a jobid, or "slurm"...is this correct?

**Comment by plazonic** [comment]
Yes, while the job is running you should be able to see it in the output of curl http://node01:9306/metrics - so that would be the first thing to verify, that the cgroup exporter is detecting slurm cgroups and finding your job.  Can you try that and report what you see there?

**Comment by jeff-avila** [comment]
Well that's odd:
[gavila1@control ~]$ curl http://node01:9306/metrics | grep slurm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5909    0  5909    0     0  2885k      0 --:--:-- --:--:-- --:--:-- 2885k

...this doesn't show up in firefox on that page....

**Comment by plazonic** [comment]
Are you sure that your system is using cgroupv2? Any output/errors from the exporter (from its init/systemd service)?

**Comment by jeff-avila** [comment]
Here's the output on the prometheus server/importer that's listening to the cgroup_exporters on the nodes:

[root@control jobstats]# curl control:9390/metrics | grep slurm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0prometheus_sd_file_mtime_seconds{filename="/usr/local/slurm/jobstats/config.d/compute.json"} 1.714679599e+09
prometheus_sd_file_mtime_seconds{filename="/usr/local/slurm/jobstats/config.d/gpu.json"} 1.714686457e+09
100 82111    0 82111    0     0  39.1M      0 --:--:-- --:--:-- --:--:-- 39.1M

**Comment by jeff-avila** [comment]
Should be v2:

[root@node01 ~]# cat /sys/fs/cgroup/cgroup.controllers
cpuset cpu io memory hugetlb pids rdma misc
[root@node01~]#

Systemd seems ok with it:

[root@node01 ~]# systemctl status cgroup_exporter.service
● cgroup_exporter.service - cgroup exporter
     Loaded: loaded (/usr/lib/systemd/system/cgroup_exporter.service; enabled; preset: disabled)
     Active: active (running) since Tue 2024-05-07 14:19:05 EDT; 12s ago
   Main PID: 3349833 (cgroup_exporter)
      Tasks: 10 (limit: 3355442)
     Memory: 11.3M
        CPU: 48ms
     CGroup: /system.slice/cgroup_exporter.service
             └─3349833 /usr/sbin/cgroup_exporter --web.listen-address=0.0.0.0:9306 --config.paths /slurm --collect.full>

May 07 14:19:05 node01 systemd[1]: Started cgroup exporter.
May 07 14:19:05 node01 cgroup_exporter[3349833]: ts=2024-05-07T18:19:05.925Z caller=cgroup_export>
May 07 14:19:05 node01 cgroup_exporter[3349833]: ts=2024-05-07T18:19:05.925Z caller=cgroup_export>
May 07 14:19:05 node01 cgroup_exporter[3349833]: ts=2024-05-07T18:19:05.925Z caller=cgroup_export>
May 07 14:19:13 node01 cgroup_exporter[3349833]: ts=2024-05-07T18:19:13.653Z caller=cgroup_export>

**Comment by jeff-avila** [comment]
So, a git clone <url> / git checkout cgroupv2 yields a directory with this line atop CHANGELOG.md:

[root@control cgroup_exporter]# cat CHANGELOG.md
## 0.9.1 / 2023-05-12

Is this right?

**Comment by plazonic** [comment]
I haven't exactly been good at updating that changelog file, sorry. Just make sure you are in the right branch and try building. E.g. 
```
grep configPaths cgroup_exporter.go 
```
should not return anything.

**Comment by jeff-avila** [comment]
Aha! That seems to have done the trick, along with editing the systemd unit file to remove the config.paths option.

Thanks!

**Comment by plazonic** [comment]
Great, good to hear it is working now! Will close this issue but please feel to reopen if needed.
