### ISSUE TITLE
Cardinality issues with prometheus

### ISSUE THREAD

**Issue by mahendrapaipuri** [PrincetonUniversity/jobstats#3]
Hello,

Firstly, this is very interesting piece of work and we are working on a similar architecture for our SLURM cluster. However, we are more interested in RAPL power metrics along with basic job CPU and memory utilisation. We are still in the process of brainstroming but I was not sure about the cardinality issues with batch jobs. Typically, there can be thousands of jobs that can submitted by several hundreds of users per day on our platform. This can make cardinality of the metrics go out of control very soon.

I would like to know your opinions based on your deployment. How big is your cluster and how many jobs are submitted typically per day? In our case, we have around 2500 nodes with half of them equipped with GPUs. If you think cardinality wont be an issue with prometheus deployed on a fat server, I would be very interested in contributing the RAPL metrics to your existing metrics.

Cheers!!

**Comment by plazonic** [comment]
We are tracking approximately some 1300 nodes, with around 130-140 having GPUs. Cardinality is a concern and our numseries is a pretty high 5 million - but Prometheus CPU usage is low (almost always less than 1 load avg) and with a year long retention we are using around 7.5TB of disk space. Oh, at least a third of these nodes see a lot of job churn, others tend to have longer/bigger jobs. Overall we can go through 4k to 16k jobs a day - rough numbers by looking at what's in kibana's slurm index.

We do have decently fast storage (NVMe though slowed down by a raid card), but we managed to get by on our old system as well which only had RAID with SAS spinning disks. There load was was higher but system was very usable.

I actually agonized over this originally and tied GPU metrics to jobs by using a separate metric for jobid and uidnumber - I am now thinking that system could have surely handled it as labels and if we switch to dcgm exporter we are likely to add them as labels as well. 

Note that some of this could be also mitigated by dropping non interesting metrics/labels. E.g. cgroup exporter collects each step/task separately - we only use overall parent (with step="", task="") stats in our regular workflow.

**Comment by mahendrapaipuri** [comment]
@plazonic Cheers for a detailed answer. Your response is indeed very encouraging and good news for us. We were even thinking about federated Prometheus deployment for scrapping all our nodes but if Prometheus handling 5 million numseries effortlessly, we should be getaway with a single instance.

> Note that some of this could be also mitigated by dropping non interesting metrics/labels. E.g. cgroup exporter collects each step/task separately - we only use overall parent (with step="", task="") stats in our regular workflow.

Agree with that! We are not interested in metrics per job step. We would like to provide aggregated metrics for each job.

Taking about cgroup_exporter, we have recently migrated to cgroups v2 and the exporter you developed currently does not handle cgroups v2 (if I am not wrong). We would be happy to extend your existing cgroup_exporter to cgroups v2 if you are willing to review.

Another important concern for us is security on Grafana datasources. As you might be aware, Grafana assembles the query on the client side and sends it to server. Once a user has permission on datasource, the user can make _any_ arbitrary query and so can have access to metrics of _all_ jobs. Have you thought about it and have any solution in WIP? The only "easy" way I am thinking about it to run a middleware that filters the queries and proxies them to Grafana server.

**Comment by plazonic** [comment]
Sorry about the delay in answering - very busy week.

You are correct that our modified cgroup_exporter does not work with cgroup v2. We are scheduled to go to RHEL9 in a few months on our next cluster and we were going to work on it then - but if you have time and inclination to help with this we would very much appreciate it. 

Regarding security or rather privacy - we are aware that folks can query job performance data from other users but at this time we do not consider it a significant privacy issue, not at our site. We do not think that much of anything significant could be gleaned from that.

**Comment by mahendrapaipuri** [comment]
@plazonic Thanks a lot for your time in answering my questions. 

We will start working on our solution soonish and we will keep an eye on the developments on your side here. 

Really appreciate your help and I will close this issue.
