### ISSUE TITLE
Queries against cgroup_exporter metrics are in a different format than jobstats expects

### ISSUE THREAD

**Issue by pmarr** [PrincetonUniversity/jobstats#4]
We're trying to implement jobstats at LSU HPC after seeing hearing about it at PEARC 2023.

With a working Slurm cluster and Prometheus collecting the [cgroup_exporter metrics by plazonic](https://github.com/plazonic/cgroup_exporter) we get the following error when querying a running job with a sufficient amount of sampling time:

```
./jobstats -c mike -p http://prometheus 132772 -d
DEBUG: jobidraw=132772, start=1694780009, end=Unknown, cluster=mike, tres=billing=64,cpu=64,mem=250G,node=1, data=, user=test123, account=test123_acct, state=RUNNING, timelimit=720, nodes=1, ncpus=64, reqmem=250G, qos=normal, partition=single, jobname=export_test
DEBUG: jobid=132772, jobidraw=132772, start=1694780009, end=1694796200.1725707, gpus=0, diff=16191.172570705414, cluster=mike, data=, timelimitraw=720
DEBUG: query=max_over_time(cgroup_memory_total_bytes{cluster='mike',jobid='132772',step='',task=''}[16191s]), time=1694796200.1725707
DEBUG: query result={'status': 'success', 'data': {'resultType': 'vector', 'result': []}}
DEBUG: query=max_over_time(cgroup_memory_rss_bytes{cluster='mike',jobid='132772',step='',task=''}[16191s]), time=1694796200.1725707
DEBUG: query result={'status': 'success', 'data': {'resultType': 'vector', 'result': []}}
DEBUG: query=max_over_time(cgroup_cpu_total_seconds{cluster='mike',jobid='132772',step='',task=''}[16191s]), time=1694796200.1725707
DEBUG: query result={'status': 'success', 'data': {'resultType': 'vector', 'result': []}}
DEBUG: query=max_over_time(cgroup_cpus{cluster='mike',jobid='132772',step='',task=''}[16191s]), time=1694796200.1725707
DEBUG: query result={'status': 'success', 'data': {'resultType': 'vector', 'result': []}}
No stats found for job 132772, either because it is too old or because
it expired from jobstats database. If you are not running this command on the
cluster where the job was run then use the -c option to specify the cluster.
If the run time was very short then try running "seff 132772".
```

The jobstats response `j` in function `get_data()` successfully queries Prometheus server but the results value sent to `get_data_out` is empty:

`{'status': 'success', 'data': {'resultType': 'vector', 'result': []}}`

Looking at the cgroup_exporter we see exports in the format:

`cgroup_memory_total_bytes{cgroup="/slurm/uid_11111/job_132772", instance="mike030:9306", job="mike_nodes"`

But jobstats expects:

`cgroup_memory_total_bytes{cluster='mike',jobid='132772',step='',task=''}[9303s])`

We can confirm metrics are actually being collected for cgroups. Running the query in Prometheus' graph manually in the cgroup_exporter format correctly returns a result for total memory.

Are we using the correct cgroup exporter and/or is there something else we are missing?

Thanks in advance.

**Comment by plazonic** [comment]
You should indeed be using https://github.com/plazonic/cgroup_exporter - that one has a bit of code to extract jobid out of cgroup path and present them as jobid label instead. The fact that you are seeing cgroup="/slurm/uid..." makes me think that you do not have the correct one - if you run cgroup_exporter do you get --collect.fullslurm option?

**Comment by plazonic** [comment]
It seems to me that you didn't add cluster label at scrape time, as part of
the Prometheus config.

Josko
