### ISSUE TITLE
Help installing jobstats

### ISSUE THREAD

**Issue by mikygit** [PrincetonUniversity/jobstats#8]
Hello, we are interested by using jobstats but so far we kinda failed to install it or at least jobstats does not produce any valid report.
I suspect it comes from the cgroups exporter, or the prometheus or slurm configuration.
For instance, there is not job_id key in the cgroups metrics (see snapshot below) )that woould match the first jobstats request.
Could not find any (more) help in the documentation ...

Would you be kind enough to help us debugging?

Thanx,

--Mike

===========CGROUPS metrics =================
= HELP cgroup_cpu_info Information about the cgroup CPUs
= TYPE cgroup_cpu_info gauge
cgroup_cpu_info{cgroup="/slurm/uid_180940xxx/job_275",cpus="0,16"} 1
cgroup_cpu_info{cgroup="/slurm/uid_180940xxx/job_276",cpus="2,18"} 1
= HELP cgroup_cpu_system_seconds Cumalitive CPU system seconds for cgroup
= TYPE cgroup_cpu_system_seconds gauge
cgroup_cpu_system_seconds{cgroup="/slurm/uid_180940xxx/job_275"} 177.67
cgroup_cpu_system_seconds{cgroup="/slurm/uid_180940xxx/job_276"} 135.6
= HELP cgroup_cpu_total_seconds Cumalitive CPU total seconds for cgroup
= TYPE cgroup_cpu_total_seconds gauge
cgroup_cpu_total_seconds{cgroup="/slurm/uid_180940xxx/job_275"} 2031.381317657
cgroup_cpu_total_seconds{cgroup="/slurm/uid_180940xxx/job_276"} 1522.228258562
= HELP cgroup_cpu_user_seconds Cumalitive CPU user seconds for cgroup
= TYPE cgroup_cpu_user_seconds gauge
cgroup_cpu_user_seconds{cgroup="/slurm/uid_180940xxx/job_275"} 1853.7
cgroup_cpu_user_seconds{cgroup="/slurm/uid_180940xxx/job_276"} 1386.61
= HELP cgroup_cpus Number of CPUs in the cgroup
= TYPE cgroup_cpus gauge
cgroup_cpus{cgroup="/slurm/uid_180940xxx/job_275"} 2
cgroup_cpus{cgroup="/slurm/uid_180940xxx/job_276"} 2
= HELP cgroup_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, goversion from which cgroup_exporter was built, and the goos and goarch for the build.
= TYPE cgroup_exporter_build_info gauge
cgroup_exporter_build_info{branch="HEAD",goarch="amd64",goos="linux",goversion="go1.20.4",revision="a0e27e49d10f2c5684e189eac9ba340fe3ff34d7",tags="netgo",version="0.9.1"} 1
= HELP cgroup_info User slice information
= TYPE cgroup_info gauge
cgroup_info{cgroup="/slurm/uid_180940xxx/job_275",jobid="275",uid="180940xxx",username="xxx"} 1
cgroup_info{cgroup="/slurm/uid_180940xxx/job_276",jobid="276",uid="180940xxx",username="xxx"} 1
= HELP cgroup_memory_cache_bytes Memory cache used in bytes
= TYPE cgroup_memory_cache_bytes gauge
cgroup_memory_cache_bytes{cgroup="/slurm/uid_180940xxx/job_275"} 4.2463232e+07
cgroup_memory_cache_bytes{cgroup="/slurm/uid_180940xxx/job_276"} 3.24128768e+08
= HELP cgroup_memory_fail_count Memory fail count
= TYPE cgroup_memory_fail_count gauge
cgroup_memory_fail_count{cgroup="/slurm/uid_180940xxx/job_275"} 0
cgroup_memory_fail_count{cgroup="/slurm/uid_180940xxx/job_276"} 0
= HELP cgroup_memory_rss_bytes Memory RSS used in bytes
= TYPE cgroup_memory_rss_bytes gauge
cgroup_memory_rss_bytes{cgroup="/slurm/uid_180940xxx/job_275"} 1.080967168e+09
cgroup_memory_rss_bytes{cgroup="/slurm/uid_180940xxx/job_276"} 1.08150784e+09
= HELP cgroup_memory_total_bytes Memory total given to cgroup in bytes
= TYPE cgroup_memory_total_bytes gauge
cgroup_memory_total_bytes{cgroup="/slurm/uid_180940xxx/job_275"} 9.223372036854772e+18
cgroup_memory_total_bytes{cgroup="/slurm/uid_180940xxx/job_276"} 9.223372036854772e+18
= HELP cgroup_memory_used_bytes Memory used in bytes
= TYPE cgroup_memory_used_bytes gauge
cgroup_memory_used_bytes{cgroup="/slurm/uid_180940xxx/job_275"} 1.130467328e+09
cgroup_memory_used_bytes{cgroup="/slurm/uid_180940xxx/job_276"} 1.413885952e+09
= HELP cgroup_memsw_fail_count Swap fail count
= TYPE cgroup_memsw_fail_count gauge
cgroup_memsw_fail_count{cgroup="/slurm/uid_180940xxx/job_275"} 0
cgroup_memsw_fail_count{cgroup="/slurm/uid_180940xxx/job_276"} 0
= HELP cgroup_memsw_total_bytes Swap total given to cgroup in bytes
= TYPE cgroup_memsw_total_bytes gauge
cgroup_memsw_total_bytes{cgroup="/slurm/uid_180940xxx/job_275"} 9.223372036854772e+18
cgroup_memsw_total_bytes{cgroup="/slurm/uid_180940xxx/job_276"} 9.223372036854772e+18
= HELP cgroup_memsw_used_bytes Swap used in bytes
= TYPE cgroup_memsw_used_bytes gauge
cgroup_memsw_used_bytes{cgroup="/slurm/uid_180940xxx/job_275"} 1.130467328e+09
cgroup_memsw_used_bytes{cgroup="/slurm/uid_180940xxx/job_276"} 1.413885952e+09
= HELP cgroup_process_exec_count Count of instances of a given process
= TYPE cgroup_process_exec_count gauge
cgroup_process_exec_count{cgroup="/slurm/uid_180940xxx/job_275",exec="/nfs/core/python/3.10/bin/python3.10"} 1
cgroup_process_exec_count{cgroup="/slurm/uid_180940xxx/job_275",exec="/usr/bin/bash"} 1
cgroup_process_exec_count{cgroup="/slurm/uid_180940xxx/job_276",exec="/nfs/core/python/3.10/bin/python3.10"} 1
cgroup_process_exec_count{cgroup="/slurm/uid_180940xxx/job_276",exec="/usr/bin/bash"} 1
= HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
= TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 2.4285e-05
go_gc_duration_seconds{quantile="0.25"} 4.6071e-05
go_gc_duration_seconds{quantile="0.5"} 5.6003e-05
go_gc_duration_seconds{quantile="0.75"} 6.6287e-05
go_gc_duration_seconds{quantile="1"} 0.000213217
go_gc_duration_seconds_sum 0.023635646
go_gc_duration_seconds_count 399
= HELP go_goroutines Number of goroutines that currently exist.
= TYPE go_goroutines gauge
go_goroutines 7
= HELP go_info Information about the Go environment.
= TYPE go_info gauge
go_info{version="go1.20.4"} 1
= HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
= TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 2.56928e+06
= HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
= TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 7.16145448e+08
= HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
= TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 4425
= HELP go_memstats_frees_total Total number of frees.
= TYPE go_memstats_frees_total counter
go_memstats_frees_total 3.492413e+06
= HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
= TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 8.036328e+06
= HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
= TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 2.56928e+06
= HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
= TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 7.41376e+06
= HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
= TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 3.989504e+06
= HELP go_memstats_heap_objects Number of allocated objects.
= TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 8345
= HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
= TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 6.340608e+06
= HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
= TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 1.1403264e+07
= HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
= TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.7133724658648033e+09
= HELP go_memstats_lookups_total Total number of pointer lookups.
= TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
= HELP go_memstats_mallocs_total Total number of mallocs.
= TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 3.500758e+06
= HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
= TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 38400
= HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
= TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 46800
= HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
= TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 288320
= HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
= TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 310080
= HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
= TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 4.194304e+06
= HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
= TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 2.349263e+06
= HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
= TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 1.179648e+06
= HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
= TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 1.179648e+06
= HELP go_memstats_sys_bytes Number of bytes obtained from system.
= TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 2.3329808e+07
= HELP go_threads Number of OS threads created.
= TYPE go_threads gauge
go_threads 21
= HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
= TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 5.31
= HELP process_max_fds Maximum number of open file descriptors.
= TYPE process_max_fds gauge
process_max_fds 262144
= HELP process_open_fds Number of open file descriptors.
= TYPE process_open_fds gauge
process_open_fds 12
= HELP process_resident_memory_bytes Resident memory size in bytes.
= TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 2.92864e+07
= HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
= TYPE process_start_time_seconds gauge
process_start_time_seconds 1.71336848913e+09
= HELP process_virtual_memory_bytes Virtual memory size in bytes.
= TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 2.195017728e+09
= HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
= TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes 1.8446744073709552e+19

**Comment by plazonic** [comment]
Make sure that you are using the correct cgroup exporter - you have to use our  modified version found at:
https://github.com/plazonic/cgroup_exporter
as only that version will parse out the jobid and output it as labels. Note also that for systems using cgroup v2 we have a different branch at the same repo (cgroupv2).

**Comment by mikygit** [comment]
Actually, we are using your crgroup exporter.
Is the v2 dedicated for more recent slurm system or is it not related at all?

And would using V1 instead of V2 explain that jobids are not outputed as labels?

**Comment by plazonic** [comment]
Forget about v2, my mistake - it wouldn't have gotten this far if that was what your system was running.

Which options are you using cgroup exporter with - in our case we do:

/usr/sbin/cgroup_exporter --config.paths /slurm --collect.fullslurm

Also, those xxx in "/slurm/uid_180940xxx/job_275" - is that you hiding the actual uid number or is it really like that?

**Comment by mikygit** [comment]
Ok so we used the same command except with --collect.proc
We'll try with --collect.fullslurm, thanx.
Ann yes xxx are quick and dirty anonymisation attemps ;-)

**Comment by plazonic** [comment]
Hm, then it should have worked. E.g. this is sample of what we see and you should get:
```
cgroup_cpu_system_seconds{jobid="55724789",step="",task=""} 27775.47
cgroup_cpu_system_seconds{jobid="55724789",step="batch",task=""} 27775.49 
cgroup_cpu_system_seconds{jobid="55724789",step="batch",task="0"} 27775.49
```
what does your /sys/fs/cgroup/cpu,cpuacct/slurm look like, e.g. we see stuff like
```
/sys/fs/cgroup/cpu,cpuacct/slurm/uid_262563/job_55786247
/sys/fs/cgroup/cpu,cpuacct/slurm/uid_262563/job_55786247/step_batch
/sys/fs/cgroup/cpu,cpuacct/slurm/uid_262563/job_55786247/step_batch/task_0
/sys/fs/cgroup/cpu,cpuacct/slurm/uid_262563/job_55786247/step_0
/sys/fs/cgroup/cpu,cpuacct/slurm/uid_262563/job_55786247/step_0/task_9
/sys/fs/cgroup/cpu,cpuacct/slurm/uid_262563/job_55786247/step_0/task_7
```
Any errors/notices coming out of cgroup_exporter? Also check
```
/usr/sbin/cgroup_exporter --help
```
to make sure you see --collect.fullslurm option - that should confirm that you are using the correct version of cgroup_exporter. Usually when we saw this kind of trouble it was because it was the non modified, "stock", version.

**Comment by mikygit** [comment]
Ok so apparentlly, we are not using the correct one.

/usr/bin/cgroup-exporter --help
usage: cgroup-exporter --config.paths=CONFIG.PATHS [<flags>]


Flags:
  -h, --[no-]help               Show context-sensitive help (also try --help-long and --help-man).
      --config.paths=CONFIG.PATHS
                                Comma separated list of cgroup paths to check, eg /user.slice,/system.slice,/slurm
      --web.listen-address=":9306"
                                Address to listen on for web interface and telemetry.
      --[no-]web.disable-exporter-metrics
                                Exclude metrics about the exporter (promhttp_*, process_*, go_*)
      --path.cgroup.root="/sys/fs/cgroup"
                                Root path to cgroup fs
      --path.proc.root="/proc"  Root path to proc fs
      --[no-]collect.proc       Boolean that sets if to collect proc information
      --collect.proc.max-exec=100
                                Max length of process executable to record
      --log.level=info          Only log messages with the given severity or above. One of: [debug, info, warn, error]
      --log.format=logfmt       Output format of log messages. One of: [logfmt, json]
      --[no-]version            Show application version.


/usr/bin/cgroup-exporter --version
cgroup_exporter, version 0.9.1 (branch: HEAD, revision: a0e27e49d10f2c5684e189eac9ba340fe3ff34d7)
  build user:       root@5bb7c17432fc
  build date:       20230512-20:01:34
  go version:       go1.20.4
  platform:         linux/amd64
  tags:             netgo

**Comment by mikygit** [comment]
hummmm, however i get roughly the same with a brand new fresh install from github ...

./cgroup_exporter --help
usage: cgroup_exporter --config.paths=CONFIG.PATHS [<flags>]


Flags:
  -h, --[no-]help               Show context-sensitive help (also try --help-long and --help-man).
      --config.paths=CONFIG.PATHS
                                Comma separated list of cgroup paths to check, eg /user.slice,/system.slice,/slurm
      --web.listen-address=":9306"
                                Address to listen on for web interface and telemetry.
      --[no-]web.disable-exporter-metrics
                                Exclude metrics about the exporter (promhttp_*, process_*, go_*)
      --path.cgroup.root="/sys/fs/cgroup"
                                Root path to cgroup fs
      --path.proc.root="/proc"  Root path to proc fs
      --[no-]collect.proc       Boolean that sets if to collect proc information
      --collect.proc.max-exec=100
                                Max length of process executable to record
      --log.level=info          Only log messages with the given severity or above. One of: [debug, info, warn, error]
      --log.format=logfmt       Output format of log messages. One of: [logfmt, json]
      --[no-]version            Show application version.

./cgroup_exporter --version
cgroup_exporter, version 0.9.1 (branch: master, revision: 64248e974a586d6fa75e0d1efc9e90c1b06785b8)
  build user:       niemaz@terra-2.int.europe.naverlabs.com
  build date:       20240418-17:01:16
  go version:       go1.22.2
  platform:         linux/amd64
  tags:             netgo

**Comment by mikygit** [comment]
Unless my git clone is buggy, it does not work:

./cgroup_exporter --config.paths /slurm --collect.fullslurm
cgroup_exporter: error: unknown long flag '--collect.fullslurm', try --help

**Comment by plazonic** [comment]
```
$ git clone https://github.com/plazonic/cgroup_exporter
Cloning into 'cgroup_exporter'...
remote: Enumerating objects: 388, done.
remote: Counting objects: 100% (388/388), done.
remote: Compressing objects: 100% (138/138), done.
remote: Total 388 (delta 195), reused 374 (delta 181), pack-reused 0
Receiving objects: 100% (388/388), 111.32 KiB | 3.09 MiB/s, done.
Resolving deltas: 100% (195/195), done.
$ cd cgroup_exporter/
$ go build
$ ./cgroup_exporter --help
usage: cgroup_exporter --config.paths=CONFIG.PATHS [<flags>]


Flags:
  -h, --[no-]help               Show context-sensitive help (also try --help-long and --help-man).
      --config.paths=CONFIG.PATHS  
                                Comma separated list of cgroup paths to check, eg /user.slice,/system.slice,/slurm
      --web.listen-address=":9306"  
                                Address to listen on for web interface and telemetry.
      --[no-]web.disable-exporter-metrics  
                                Exclude metrics about the exporter (promhttp_*, process_*, go_*)
      --path.cgroup.root="/sys/fs/cgroup"  
                                Root path to cgroup fs
      --[no-]collect.fullslurm  Boolean that sets if to collect all slurm steps and tasks
      --log.level=info          Only log messages with the given severity or above. One of: [debug, info, warn, error]
      --log.format=logfmt       Output format of log messages. One of: [logfmt, json]
      --[no-]version            Show application version.
```

**Comment by mikygit** [comment]
Ok yes, pls apologise, I re-cloned and re-built and it works.
At least ./cgroup_exporter --config.paths /slurm --collect.fullslurm did.

Thanx a lot!

**Comment by plazonic** [comment]
Wonderful. We can keep this open for a bit longer until you are certain things are working.

**Comment by mikygit** [comment]
Also, related gpu data are not stored either, eich as gpu_total_memory, gpu_used_memory or gpu_utilization.
Is this supposed to be handled by the cgroup exporter as well?

If i force self.gpus = 0 and removed cluster key from the queries, I managed to get info related to cpus:

```
./jobstats -f 277

================================================================================
                              Slurm Job Statistics
================================================================================
         Job ID: 277
  NetID/Account: xxx/xxxlab
       Job Name: encod
          State: RUNNING
          Nodes: 1
      CPU Cores: 2
     CPU Memory: 6GB (3GB per CPU-core)
  QOS/Partition: normal/gpu
        Cluster: xxx-hpc
     Start Time: Fri Apr 19, 2024 at 3:00 PM
       Run Time: 01:07:24 (in progress)
     Time Limit: 5-00:00:00

                              Overall Utilization
================================================================================
  CPU utilization  [|||||||                                        15%]
  CPU memory usage [                                                0%]

                              Detailed Utilization
================================================================================
  CPU utilization per node (CPU time used/run time)
      terra-2: 00:19:50/02:14:49 (efficiency=14.7%)

  CPU memory usage per node - used/allocated
      terra-2: 1.0GB/8192.0TB (535.9MB/4096.0TB per core of 2)

                                     Notes
================================================================================
  * The overall CPU utilization of this job is 15%. This value is low compared
    to the target range of 90% and above. Please investigate the reason for
    the low efficiency. For instance, have you conducted a scaling analysis?
    For more info:
      https://researchcomputing.princeton.edu/get-started/cpu-utilization

  * Have a nice day!
```

In my particular setting, I have only one cluster of multiple machines and nodes.
In your sample config, I can not figure out if 'tiger' is a cluster or a simple machine/node since you allocate default memory per core to tiger. Which tells me it's rather a machine/node in your cluster X. Unless you have one machine per cluster or, even better, all the nodes on the tiger cluster have the same amount of cores and mem per core .... which could make sense ... right

Ok anyway it's getting there, somehow.
I found a way to overcome the cluster pb bt removing it from queries.
Have to find out how to get gpu info into prometheuse now...

**Comment by mikygit** [comment]
I'll dig into the nvidia_gpu_prometheus_exporter for the gpu info missing

**Comment by plazonic** [comment]
First, regarding cluster label - that's to be assigned at scrape time, in prometheus config. E.g. this is what we've got (for tiger):
```
- job_name: Tiger Nodes
  scrape_interval: 30s
  scrape_timeout: 30s
  file_sd_configs:
  - files:
    - "/etc/prometheus/local_files_sd_config.d/tigernodes.json"
  metric_relabel_configs:
  - source_labels:
    - __name__
    regex: "^go_.*"
    action: drop
```
And then tigernodes.json has things like 
```
[
  {
    "labels": {
      "cluster": "tiger",
      "service": "compute"
    },
    "targets": [
      "tiger-h19c1n10:9100",
      "tiger-h19c1n10:9306",
      "tiger-h19c1n11:9100",
      "tiger-h19c1n11:9306",
....
```
We do it this way because we have a separate job dynamically creating a list of nodes and their exporters that need to be scraped. You could also do something what we do for login nodes:
```
- job_name: Tiger Login Nodes
  scrape_interval: 30s
  scrape_timeout: 30s
  static_configs:
  - targets:
    - tigerlogin1:9100
    - tigerlogin2:9100
    labels:
      cluster: tiger
      service: login
```
Note the labels. This is the correct spot to add them and allows one prometheus instance to be shared among many clusters (in our case currently 5 clusters of varying sizes).

As far as GPUs - that's a different exporter that you need to run in addition to cgroup exporter (and node_exporter, and gpfs_exporter in our case, though that one runs just on one machine). I think we link to that one  on this repo and all the stuff that needs to be done to make it work (there is pre/post job thing that helps in tracking which job "owned" the GPU so that gpu exporter can collect that info - you have to follow all of that for it to work). We also have two different exporters - the old nvml one and dcgm based one (that we will switch to but haven't started fully using yet).

As far as what tiger is - it's a cluster and yes, all nodes have the same number of cores though a few dozen have more memory than the rest ("fat" nodes).

**Comment by plazonic** [comment]
Hello,

have you managed to get it all working?

**Comment by mikygit** [comment]
Yes, thank you very much!
Still have to set up grafana but it's postponed for now.


Le jeu. 20 juin 2024 à 16:54, Josko Plazonic ***@***.***> a
écrit :
